project:
  type: website

website:
  title: "tech.bchartier.net"
  page-navigation: false
  
  sidebar:
    title: Table des matières
    style: "docked"
    search: true
    contents: auto
    collapse-level: 1

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
