# Richesse du langage

Les possibilités du langage SQL sont bien plus importantes que ce que le présent document présente. Même si certaines requêtes n’en contiennent pas il est quasiment toujours possible d’y ajouter des filtres, des agrégations, des sous-requêtes et de combiner avec des opérateurs logiques les résultats de différentes requêtes.

# Aller au-delà des exemples de base

Le présent document constitue un aide-mémoire pour les besoins les plus courants. Pour plus de détails se référer aux documentations officielles et aux aides en ligne mises à disposition par des tiers :


## Doc officielle de PostgreSQL

* https://www.postgresql.org/docs/current/index.html [doc complète de PostgreSQL]
* https://www.postgresql.org/docs/current/sql-commands.html [commandes SQL supportées par PostgreSQL]
* https://www.postgresql.org/docs/current/sql-syntax.html [chapitre consacré à la syntaxe SQL]


## Doc officielle de PostGIS

* https://postgis.net/docs/manual-3.2/ [doc complète de PostGIS 3.2]
* https://postgis.net/docs/manual-3.2/reference.html [référence de PostGIS 3.2]


## Supports didactiques

* https://www.postgresql.org/docs/current/tutorial.html [tuto PostgreSQL officiel]
* https://www.geeksforgeeks.org/postgresql-tutorial/ [PostgreSQL - GeeksForGeeks]
* https://www.w3schools.blog/postgresql-tutorial [PostgreSQL - W3schools]
* https://postgis.net/workshops/fr/postgis-intro/ [PostGIS en français]
* https://postgis.net/workshops/en/postgis-intro/ [PostGIS en anglais]